04_Rails1/app/config/routes.rb
Rails.application.routes.draw do
  resources :people
  root to: 'people#index'
end

04_Rails1/app/app/models/person.rb
class Person
  include ActiveModel::Model
  attr_accessor :first_name, :last_name, :description
end

04_Rails1/app/app/controllers/people_controller.rb
class PeopleController < ApplicationController

  # GET /people
  # GET /people.json
  def index
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    if @person.valid?
      session[:first_name] = @person.first_name
      session[:last_name] = @person.last_name
      session[:description] = @person.description

      redirect_to people_path
    else
      render :new
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :description)
    end
end

04_Rails1/app/app/helpers/people_helper.rb
module PeopleHelper
end

04_Rails1/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div class="container">
 	<p>
 		<%= image_tag 'http://www.pjwstk.edu.pl/templates/pjwstk/images/logo-lg-md.png' %>
 	</p>
 	<%= yield %>
 </div>


</body>
</html>

04_Rails1/app/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

04_Rails1/app/app/views/people/index.html.erb
<h1>Wprowadzona osoba</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= session[:first_name] %></td>
      <td><%= session[:last_name] %></td>
      <td><%= session[:description] %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'Ustaw osobę', new_person_path %>

04_Rails1/app/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>